default:
  image: hugomods/hugo:exts

test:  # builds and tests your site
  script:
    - hugo --cleanDestinationDir --ignoreCache
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

create-pages:
  stage: deploy
  script:
    - pwd
    - git log -1
    - hugo --cleanDestinationDir --ignoreCache --gc
  pages: true
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
