baseURL      = 'https://mattijuntti.net'
languageCode = 'en-us'
title        = "Matti's CS Notebook"

[markup]
    [markup.highlight]
        style = "bw"
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
            enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)'], ['$', '$']]

[params]
math = true

[[menus.main]]
name    = 'Home'
pageRef = '/'
weight  = 10

[[menus.main]]
name    = 'Completed exercises'
pageRef = '/completed-exercises'
weight  = 20

# [[menus.main]]
# name    = 'Tags'
# pageRef = '/tags'
# weight  = 30

# [module]
#   [module.hugoVersion]
#     extended = false
#     min = "0.116.0"
