baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CS Notebook'
theme = 'csnotebook'


[markup]
    [markup.highlight]
        codeFences = false  # default is true
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
            enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)'], ['$', '$']]

[params]
math = true
