baseURL      = '/'
languageCode = 'en-us'
title        = 'CS Notebook'
theme        = 'csnotebook'

[markup]
    [markup.highlight]
        style = "bw"
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
            enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['\[', '\]'], ['$$', '$$']]
                    inline = [['\(', '\)'], ['$', '$']]

[params]
math = true
